### ISSUE TITLE
Drop Stancy CMS and upgrade Laravel/PHP

### ISSUE THREAD

**Issue by Gummibeer** [Astrotomic/astrotomic.info#7]
Stancy is limited to Laravel v6 or so and we are therefore limited to this Laravel version and because of this to older dependencies.
Stancy is only a wrapper around several spatie packages - primary the sheets.
We are good to go without Stancy and use the sheets and other packages directly in the latest version.

**Comment by scrlkx** [comment]
I've made some progress here: [scrlkx/patch-2](https://github.com/scrlkx/astrotomic.info/tree/patch-2) in case you're interested.

**Comment by scrlkx** [comment]
Upgrading `spatie/packagist-api` to v2 we will need to deal with [astrotomic/laravel-medialibrary-hls](https://packagist.org/packages/astrotomic/laravel-medialibrary-hls). Packagist new API does not give us its metadata as it was considered deprecated. Maybe there is an alternative besides dropping it, but as it doesn't have any installation I thought you might want to do that.

Checkout: https://blog.packagist.com/deprecating-composer-1-support

**Comment by Gummibeer** [comment]
Hey,
The HLS package is still pending and WIP. So it's fine if it's not listed - as there's nothing special with that package it should be listed as soon as it's finished. 🤔
Will check out the link - thanks for sharing and mentioning. 🥳

**Comment by scrlkx** [comment]
Sorry, I didn't see what the package was about and I got the impression it was an old abandoned project. I'll just ignore it until you've it working on API v2.

**Comment by Gummibeer** [comment]
You don't have to wait. It won't be finished in next few weeks.
So just proceed and ignore the package.

PS: really thanks for taking the time to upgrade the website! 🤩🥳

**Comment by scrlkx** [comment]
I'm going to replace Stancy `SitemapFactory` by [spatie/laravel-sitemap](https://github.com/spatie/laravel-sitemap) unless you've thought on another way. Also, let's go straight to Laravel 8 and PHP 8 as well.

**Comment by Gummibeer** [comment]
The factory was only a wrapper around.
